server:
  port: ${port:6001}
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: 5MB

spring:
  application:
    name: user-service
  profiles:
    active: dev
  banner:
    location: classpath:banner/banner.txt

# 日志级别
logging:
  level:
    root: info